Adding test case for user defined identifier in REDUCTION clause but failed.
The error is as follows.

../parseOmp -rose:C_only --edg:no_warnings -w -rose:verbose 0 --edg:restrict -rose:openmp -rose:openmp:ast_only -I../../../../../../../rose_src/src/frontend/SageIII -c ../../../../../../../rose_src/tests/nonsmoke/functional/CompileTests/OpenMP_tests/cvalidation/for_firstprivate.c
Error: getType(): default reached: declaration = 0x7f42819cd928 = SgVariableDeclaration
parseOmp[18654] 0.05937s Rose[FATAL]: assertion failed:
parseOmp[18654] 0.05942s Rose[FATAL]:   /export/tmp.rose-mgr/jenkins/edg4x/workspace/development-edg-binary-RMC/COMPILER/gcc-5.4.0-default/EDGVERSION/4.9/src/frontend/CxxFrontend/EDG/edgRose/edgRose.C:26170parseOmp[18654] 0.05946s Rose[FATAL]:   SgType* EDG_ROSE_Translation::getType(SgDeclarationStatement*)
parseOmp[18654] 0.05949s Rose[FATAL]:   required: type != __null